Repository institute-atri/glogger, pull requests merged in 2024-03, with the labels that each got.

#17 feat/docs#16: create documentation in readme
  README.md
Labels: documentation

#19 bug(#18): glogger is being recognized as a program and not an import
  concat.go
  global.go
  logger.go
  printer.go
Labels: bug

#21 feat(ci/cd): create CI, dependabot.yml and update go version
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  go.mod
Labels: enhancement
